{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.nfc",
    "module": "nfc.rc522",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "nfc.rc522-1.0.1.aar",
          "url": "nfc.rc522-1.0.1.aar",
          "size": 25681,
          "sha512": "c3892cf9237f0501db46ffbdf8641e8195a3c567f24a35542261bc50720df444a55226e8f3d7a8c73d22f50e36a15063c791e159c4dad530ca23a542d99e8395",
          "sha256": "a4a7195db635474d6c24d87f4a3a8bffc1152ae66b3e7f986c8886fa0d0e4f7b",
          "sha1": "f862bdecb2a2f17a49c656aa3bd5c0f027128607",
          "md5": "ff15b3997e910b4d09b1354d17bb3e98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.serialport",
          "module": "serialport",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "nfc.rc522-1.0.1.aar",
          "url": "nfc.rc522-1.0.1.aar",
          "size": 25681,
          "sha512": "c3892cf9237f0501db46ffbdf8641e8195a3c567f24a35542261bc50720df444a55226e8f3d7a8c73d22f50e36a15063c791e159c4dad530ca23a542d99e8395",
          "sha256": "a4a7195db635474d6c24d87f4a3a8bffc1152ae66b3e7f986c8886fa0d0e4f7b",
          "sha1": "f862bdecb2a2f17a49c656aa3bd5c0f027128607",
          "md5": "ff15b3997e910b4d09b1354d17bb3e98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nfc.rc522-1.0.1-sources.jar",
          "url": "nfc.rc522-1.0.1-sources.jar",
          "size": 9231,
          "sha512": "5ebae1dcabcfc452833c56b12d478c8475ca59a3bd46170014e75d659c8648dca2eb9e7a986b9ecd99dc1012e40a775e9e494f79d610db60b9cb4c910a97df42",
          "sha256": "c3fcaa2a89f0c3f5864c3995867b98d00162acbf9b5a8d21838d4d3c6ab98e91",
          "sha1": "40eee80a7a0610f496b14feb68b01936a13605f9",
          "md5": "e6641cadbc0f95f6902b7982fdd67948"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nfc.rc522-1.0.1-javadoc.jar",
          "url": "nfc.rc522-1.0.1-javadoc.jar",
          "size": 330974,
          "sha512": "d8c499534a0a5ead5a991b8aba97d621ebe484de2c56ec9f8de4d9c49f3c192649c4e5906524e1e49781493584c5f101df99bf898e92f23b3b7f0dad9d02fa16",
          "sha256": "4f7659ca2622bdfec39c39fcb23763d9852f48620a7a296631989d1dec3e789c",
          "sha1": "8cc60e5b72feaff4af29abc352d1b823a395c044",
          "md5": "beb784ed64c8410d181b682dc9034b2a"
        }
      ]
    }
  ]
}
