{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.iconsolepro",
    "module": "api-https-sdk",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.5.aar",
          "url": "api-https-sdk-1.0.5.aar",
          "size": 155533,
          "sha512": "915957340192190632b0080e16d7e1ca20218ad662af5e8a609e9399714116c1e42a4c47928caa220305a1d3c212e334c2baa40f0fce988cffa0879f0fd97139",
          "sha256": "d8fdb529b5c05ba0c8c2736c9dcd4859eb3e2b17b125c61b2b814e31d381fcff",
          "sha1": "b193dad3d4b7adc9185079ed10833a7b8d42f4f9",
          "md5": "151bb9f8af85d6dc47e757983845e0e8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.5.aar",
          "url": "api-https-sdk-1.0.5.aar",
          "size": 155533,
          "sha512": "915957340192190632b0080e16d7e1ca20218ad662af5e8a609e9399714116c1e42a4c47928caa220305a1d3c212e334c2baa40f0fce988cffa0879f0fd97139",
          "sha256": "d8fdb529b5c05ba0c8c2736c9dcd4859eb3e2b17b125c61b2b814e31d381fcff",
          "sha1": "b193dad3d4b7adc9185079ed10833a7b8d42f4f9",
          "md5": "151bb9f8af85d6dc47e757983845e0e8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-https-sdk-1.0.5-sources.jar",
          "url": "api-https-sdk-1.0.5-sources.jar",
          "size": 34274,
          "sha512": "f91b48e745adf62999325e77b3e2f1f1e84fde0edd00bbde3730d6421211a99f3f5070ef89c53b4e265597ccb18dd282bbb6bd5d41e4f22059811e34b0b87a36",
          "sha256": "0a30619a7f78c5c0f0dd71711ad26a68adb6a86f0ddbf8ea18fdb41e9154fe91",
          "sha1": "ebe58a8fd6835f171d8947339e5e8847113dfda9",
          "md5": "d4304aef65ee9006e5f25798e2d419ac"
        }
      ]
    }
  ]
}
