{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.iconsolepro",
    "module": "api-https-sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.1.aar",
          "url": "api-https-sdk-1.0.1.aar",
          "size": 137927,
          "sha512": "37f8267a4ce6a814eedef15440577cd86eebd3469784be152e3fbd94d87d0ed00580152d8a4015c8940264bc2f7d29f7371cd7a23f5680b0ac195a6b7fa47670",
          "sha256": "029c2c2ba393cade1e0571cfbc066a6a61268fbc9165466ddf2b6410a5bccf5a",
          "sha1": "8b32e79bfa08354ac7ef94b5239b0bde790668f8",
          "md5": "5ebc05392a42dfcf3cb3836e1ea4d7fe"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.1.aar",
          "url": "api-https-sdk-1.0.1.aar",
          "size": 137927,
          "sha512": "37f8267a4ce6a814eedef15440577cd86eebd3469784be152e3fbd94d87d0ed00580152d8a4015c8940264bc2f7d29f7371cd7a23f5680b0ac195a6b7fa47670",
          "sha256": "029c2c2ba393cade1e0571cfbc066a6a61268fbc9165466ddf2b6410a5bccf5a",
          "sha1": "8b32e79bfa08354ac7ef94b5239b0bde790668f8",
          "md5": "5ebc05392a42dfcf3cb3836e1ea4d7fe"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-https-sdk-1.0.1-sources.jar",
          "url": "api-https-sdk-1.0.1-sources.jar",
          "size": 33818,
          "sha512": "6a81c4c825a2e88d64923d682a7701f88b3c762bce4c05b31036cc554ec6858d1fef1cf7e94d6f728e7efb633ef045e2537547219c9bab51998f72d021802b03",
          "sha256": "7212a8360171893304612dfb5ac313b932c928e69defea77d481234496530f64",
          "sha1": "72925b547f2076c65cb15feff7b1e31dcb87f9ba",
          "md5": "8735ee32a5df191341bef7cb6dbb02c2"
        }
      ]
    }
  ]
}
