{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.iconsolepro",
    "module": "api-https-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.2.aar",
          "url": "api-https-sdk-1.0.2.aar",
          "size": 144107,
          "sha512": "615ac0d1f033c0865ed824fcdc4001f0d27cd1d8c47385efd18940d9f61ab45abd9c8cd36592d02833fc74979674d18433825798829c37b86ff62bb94047bfb3",
          "sha256": "29414d27a2d3ab5ec2e487d7bd804c6862ac41efefec7c4fac8ab7aecfcb2ec2",
          "sha1": "7be3350f1f6d12d046ca07029275385d52f938d8",
          "md5": "3f6e51b822efd1b10e1efad6a822c42d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.2.aar",
          "url": "api-https-sdk-1.0.2.aar",
          "size": 144107,
          "sha512": "615ac0d1f033c0865ed824fcdc4001f0d27cd1d8c47385efd18940d9f61ab45abd9c8cd36592d02833fc74979674d18433825798829c37b86ff62bb94047bfb3",
          "sha256": "29414d27a2d3ab5ec2e487d7bd804c6862ac41efefec7c4fac8ab7aecfcb2ec2",
          "sha1": "7be3350f1f6d12d046ca07029275385d52f938d8",
          "md5": "3f6e51b822efd1b10e1efad6a822c42d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-https-sdk-1.0.2-sources.jar",
          "url": "api-https-sdk-1.0.2-sources.jar",
          "size": 34085,
          "sha512": "c2e15d566b7c2676aa60492e45ae87777112650c709f427d9ebf81f1f8e1b2f3f2d88791aac05f3720e921a5b02a991b01a867d8fed6507dfd5803c731b7b93d",
          "sha256": "6479c47835e58205bffc72340751b9ab767aeb854234f7359dd2be0f7a1f2869",
          "sha1": "688c0e3aa05b58e242ae2fd787e4d79134679f3b",
          "md5": "4f977ec28934e5ffd73ee0f611cd5491"
        }
      ]
    }
  ]
}
