{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.nfc",
    "module": "nfc.rc522",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "nfc.rc522-1.0.0.aar",
          "url": "nfc.rc522-1.0.0.aar",
          "size": 22011,
          "sha512": "b8c18db56afc196d19335834f99e295997fda6ef16ee9911333ed2da9010a99695883c854bf55cb36790372d09caa1b02151edf1534cc032d6cdfdf1c025d541",
          "sha256": "99f1ca9ff3460a0080323a2eaa198c83213aaf78919532cdfc94d891b13ed076",
          "sha1": "f9021734491eda096f1ff22718d0e0d55d9b2c0a",
          "md5": "ccacef32391f26e7341f151b1940bf00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.serialport",
          "module": "serialport",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "nfc.rc522-1.0.0.aar",
          "url": "nfc.rc522-1.0.0.aar",
          "size": 22011,
          "sha512": "b8c18db56afc196d19335834f99e295997fda6ef16ee9911333ed2da9010a99695883c854bf55cb36790372d09caa1b02151edf1534cc032d6cdfdf1c025d541",
          "sha256": "99f1ca9ff3460a0080323a2eaa198c83213aaf78919532cdfc94d891b13ed076",
          "sha1": "f9021734491eda096f1ff22718d0e0d55d9b2c0a",
          "md5": "ccacef32391f26e7341f151b1940bf00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nfc.rc522-1.0.0-sources.jar",
          "url": "nfc.rc522-1.0.0-sources.jar",
          "size": 7861,
          "sha512": "c9d91e62bbe391d70c4e32e1ce85ee3f103710a5140c2504e0d1c52ba2732799edd7338d1f6851a314906365df5c163c515721698ec27b1b95b4e0bb1046d92a",
          "sha256": "fde0fe1528f8b73bfa3f198f0ce6ef1383bd60fb6cb695460dd627d7159d31ee",
          "sha1": "1ed0af5f7ad7b65ac07f8e66a63a3a668f280d32",
          "md5": "c126f445622995762ee80cdf5d44c673"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nfc.rc522-1.0.0-javadoc.jar",
          "url": "nfc.rc522-1.0.0-javadoc.jar",
          "size": 315042,
          "sha512": "e3347109a0c2369ebd1badae4b0288f2a43c175c369ddd211d8e442ce46f1fb319f46493292f6211255120c73615886ea7d1540b3e97b62c4fa27c5c4bd43a80",
          "sha256": "90fab8a996065d7e86be09c0cf608d4e1fa5b32c8224791edcd032b3ccc72850",
          "sha1": "04e2486619189bdba4852c3da2fef25b3ffa0aab",
          "md5": "ce20b65ae5d4c1d522c49df108081d27"
        }
      ]
    }
  ]
}
