{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.ai",
    "module": "ai-nlp-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ai-nlp-sdk-1.0.0.aar",
          "url": "ai-nlp-sdk-1.0.0.aar",
          "size": 13299,
          "sha512": "ed7d2bebca02b54bea6bb774a1e664f737ea2a8ded3bc4214dfe479c87d5e9966237c4e89031fabbf9a8e81bb2327aed64d33dee76a33611bbefa687a4b0a6ed",
          "sha256": "c6069ff016c921cd77584a4e5e0b4dbc15bab21665a5a6e1333bd854bda84ad0",
          "sha1": "625d177806caf104ba88d935e26aa07831f15b3c",
          "md5": "9ca78d4618dec076b20e2f22d046b688"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ai-nlp-sdk-1.0.0.aar",
          "url": "ai-nlp-sdk-1.0.0.aar",
          "size": 13299,
          "sha512": "ed7d2bebca02b54bea6bb774a1e664f737ea2a8ded3bc4214dfe479c87d5e9966237c4e89031fabbf9a8e81bb2327aed64d33dee76a33611bbefa687a4b0a6ed",
          "sha256": "c6069ff016c921cd77584a4e5e0b4dbc15bab21665a5a6e1333bd854bda84ad0",
          "sha1": "625d177806caf104ba88d935e26aa07831f15b3c",
          "md5": "9ca78d4618dec076b20e2f22d046b688"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ai-nlp-sdk-1.0.0-sources.jar",
          "url": "ai-nlp-sdk-1.0.0-sources.jar",
          "size": 12808,
          "sha512": "04d7d433c40cc513d6777ffcfc45123ed3e3c1964b1456d9d03873b7fedf2c0f9aa92af216222b281d7297f9af59e61031a5cc63989b99f93f7a3784d5beb8ff",
          "sha256": "8150afccd7fae06bffff061cee461880e3c4b2fe947d39a2424f79830a3c0d03",
          "sha1": "200c0384805062678d7237146b5679790498a597",
          "md5": "fd50a2d6d3eb7f87379fc22efb8d2e76"
        }
      ]
    }
  ]
}
