{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.ai",
    "module": "aliyun-asr-lib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aliyun-asr-lib-1.0.1.aar",
          "url": "aliyun-asr-lib-1.0.1.aar",
          "size": 75288,
          "sha512": "da18ef799749f23b7dee9536ce432f6cc5723d4c457098067c5cc2f775fde6cea2b203230e1eac8d45c3220db415cf2367d2732b92c13b7a3398bef91f0518be",
          "sha256": "ea25d32deefda78d150edafe6b1c2f73f6a8ca4410007aec30611665fea5b61d",
          "sha1": "934cf93c7b74f9ca76ea7fa69b6cf1284d04e70b",
          "md5": "b8c0ee96385372b314a913f9dd722664"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aliyun-asr-lib-1.0.1.aar",
          "url": "aliyun-asr-lib-1.0.1.aar",
          "size": 75288,
          "sha512": "da18ef799749f23b7dee9536ce432f6cc5723d4c457098067c5cc2f775fde6cea2b203230e1eac8d45c3220db415cf2367d2732b92c13b7a3398bef91f0518be",
          "sha256": "ea25d32deefda78d150edafe6b1c2f73f6a8ca4410007aec30611665fea5b61d",
          "sha1": "934cf93c7b74f9ca76ea7fa69b6cf1284d04e70b",
          "md5": "b8c0ee96385372b314a913f9dd722664"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "aliyun-asr-lib-1.0.1-sources.jar",
          "url": "aliyun-asr-lib-1.0.1-sources.jar",
          "size": 51853,
          "sha512": "184fa2649fc5ec6a243994309c57245ba1a9443b2c9b23c88efcf911b67536625272e30e72a2a682f9df8f1e75925de389e74a26167d79eefda07ce1b21289c4",
          "sha256": "9b609e7edb6275a07ac78739d8919e224a28ec045faa100ec9c9b60b241f2708",
          "sha1": "063f33b7c3024bb1a1b8888a00f366c537538990",
          "md5": "58136b791a690b34e20b7e703046d735"
        }
      ]
    }
  ]
}
