{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.iconsolepro",
    "module": "api-https-sdk",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.3.aar",
          "url": "api-https-sdk-1.0.3.aar",
          "size": 144108,
          "sha512": "f5da5a6f50cc29ec8f256480eea2711463eb6d1eb6fb457ca5bbdd4733495f317ff1f796b37ff6b96e3799fbbe2514e48a6640e9dbb1741877d93e41afac0bc5",
          "sha256": "6b4e1b10e09f17e1b13ec327d7bcb7bca4804dbe57bf12c55ec6e40db61a97ea",
          "sha1": "97ea2bc3417cdd1133f4daa66693fc76f4452615",
          "md5": "ec4f296593363dc1d63237659b3dda43"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-https-sdk-1.0.3.aar",
          "url": "api-https-sdk-1.0.3.aar",
          "size": 144108,
          "sha512": "f5da5a6f50cc29ec8f256480eea2711463eb6d1eb6fb457ca5bbdd4733495f317ff1f796b37ff6b96e3799fbbe2514e48a6640e9dbb1741877d93e41afac0bc5",
          "sha256": "6b4e1b10e09f17e1b13ec327d7bcb7bca4804dbe57bf12c55ec6e40db61a97ea",
          "sha1": "97ea2bc3417cdd1133f4daa66693fc76f4452615",
          "md5": "ec4f296593363dc1d63237659b3dda43"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-https-sdk-1.0.3-sources.jar",
          "url": "api-https-sdk-1.0.3-sources.jar",
          "size": 34079,
          "sha512": "ce379c686185d07b9b6b32901d4d84368388bf92b8a5f1d5bf40d00e92791cd3f38cd23032a04c7caa48b3508b30f057dfefb3bbaaadacec9dbcc44a3cd3b77b",
          "sha256": "82cafd118d13dba1823ff5ce46f4c0a9396bf214d0cc9e845340c012776ced9d",
          "sha1": "4613c0cd0ca0b88407b4636166cc7dd6db4583d7",
          "md5": "2986ea7b9bcc60ca7aa34e216b616d78"
        }
      ]
    }
  ]
}
